<div class="separator" style="clear: both;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEioNtwKn5NPfqmd5pWFVSaDfPEvEFk3pYP0x_pwHpcWm2NSDKcHLWrrs9nu8FucteWhNIk8jfWcVAfi4vw4Gv25ycDj4cC2mK6pJKonZugcREPQxjaOv9YpL5mIb4NvmKB2FiztMjD7WGvVMdS6xaFyS-r1NHuKe9M102d4aAwE19Eu-LNkWoYZ2PFe2Ql_/s1536/ChatGPT%20Image%2011%20Nov%202025,%2019.27.54.png" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" height="320" data-original-height="1536" data-original-width="1024" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEioNtwKn5NPfqmd5pWFVSaDfPEvEFk3pYP0x_pwHpcWm2NSDKcHLWrrs9nu8FucteWhNIk8jfWcVAfi4vw4Gv25ycDj4cC2mK6pJKonZugcREPQxjaOv9YpL5mIb4NvmKB2FiztMjD7WGvVMdS6xaFyS-r1NHuKe9M102d4aAwE19Eu-LNkWoYZ2PFe2Ql_/s320/ChatGPT%20Image%2011%20Nov%202025,%2019.27.54.png"/></a></div> # These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
